### ISSUE TITLE
Feature Request: Assign colors per event type

### ISSUE THREAD

**Issue by sergeifilippov** [staempfli/magento2-module-hipchat#1]
Would you be open to a pull request which allows for customisation of colors per event?

## Example

- Failed Admin Login = Red
- Successful Order = Green
- etc

## Reasons

Having a single color for all items can be problematic. You might want to have red color for failed logins as it's a negative event which green for an order makes more sense as it is a positive event.

**Comment by mhauri** [comment]
Hi @sergeifilippov sure we will be open for PR's feel free to submit one.

**Comment by mhauri** [comment]
@sergeifilippov I will close this issue, feel free to provide a Pull Request to implement this feature.
